apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  annotations:
    github.com/project-slug: nmushino/quarkusdroneshop-counter
spec:
  type: other
  lifecycle: unknown
  owner: quarkusdroneshop
